# Generated by Django 2.2.4 on 2019-08-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='destination',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AddField(
            model_name='routes',
            name='origin',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
